### PR TITLE
Added support for list permission schemes. They are set in the list config in sitehierarchy.json.

### PR DESCRIPTION
**Pull request by olemp**
…onfig in sitehierarchy.json.

### CODE REVIEW

**Comment by olemp** [comment]
Sample JSON is found here https://jsonblob.com/555335bfe4b05c29a670f252.

**Comment by olemp** [comment]
The pull request 'Added support for custom permission levels' was merged into the same pull request.

**Comment by olemp** [comment]
Sample for 'Added support for custom permission levels' found here https://jsonblob.com/5553450ee4b05c29a670f32c.

**Comment by tarjeieo** [comment]
Looks good - the way associated groups are handled is up for debate - but i don't have a better suggestions at the moment.

**Pull request merged**
